<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc5f473acbfeca9b1e0310debeba4722e
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'MyClub\\MyClubBooking\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'MyClub\\MyClubBooking\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc5f473acbfeca9b1e0310debeba4722e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc5f473acbfeca9b1e0310debeba4722e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc5f473acbfeca9b1e0310debeba4722e::$classMap;

        }, null, ClassLoader::class);
    }
}
