<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'MyClub\\MyClubBooking\\' => array($baseDir . '/src'),
    'MyClub\\Common\\' => array($vendorDir . '/myclub/common-lib/src'),
);
